#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create Mesh
runApplication blockMesh

# integrate tables
runApplication canteraToFoam

# decompose case
runApplication decomposePar

# start solver
runParallel flameletFoam 4

# reconstruct case
runApplication reconstructPar

rm -rf processor*

# calculate species mass fractions
runApplication flameletFoamPost -latestTime

# ----------------------------------------------------------------- end-of-file
